---
- name: Install Bash
  pacman: name={{ item }} state=present
  with_items:
    - bash
    - bash-completion
  tags:
    - shell

- name: Install ZSH
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
  tags:
    - shell

- name: Install Fish
  pacman: name={{ item }} state=present
  with_items:
    - fish
    - powerline
    - powerline-fonts
  tags:
    - shell

- name: Install dependencies for fish-ccat.
  pip: name={{ item }} state=present
  with_items:
    - pygments
    - pygments-style-solarized
